#!/bin/bash

##########
#Author - Yash Dhawan
#Date - 15.01.2026
#Purpose - My first Bash Script to print Hello
#Version - v1
##########

set -x #debug mode

echo "Hello devops this is my first bash script"
