#!/bin/bash

##########
#Author - Yash Dhawan
#Date - 16.01.2026
#Purpose - Input File name and check if exist
#Version - v1
##########

#set -x #debug mode
set -e #exit if error 

echo "Enter your $filename:"
read filename

if [ -f "$filename" ]; then 
echo "$filename exist" 

else  
echo "$filename does not exist"

fi
